AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/support/*'
    - 'spec/spec_helper.rb'
    - 'Rakefile'
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 120
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
